---
- hosts: webserver
  remote_user: vagrant
  become: yes
  roles:
    - webserver

- hosts: webdatabase
  remote_user: vagrant
  become: yes
  roles:
    - webserver
    - database

- hosts: linux-desktop
  remote_user: joona
  become: yes
  roles:
    - linux-desktop

- hosts: windows-desktop
  roles:
    - windows-desktop
