---
- name: install winSCP
  win_chocolatey:
    name: winscp.install
    state: present

- name: install notepad++
  win_chocolatey:
    name: notepadplusplus.install
    state: present

- name: install putty
  win_chocolatey:
    name: putty.install
    state: present

- name: create ansible directory
  win_file:
    path: C:\ansible
    state: directory

- name: copy wallpaper image to created directory
  win_copy:
    src: roles/windows-desktop/files/arctic.jpeg
    dest: C:\ansible\

- name: change wallpaper
  win_regedit:
    key: HKCU:\Control Panel\Desktop
    value: Wallpaper
    data: C:\ansible\arctic.jpeg

- name: make wallpaper fullscreen
  win_regedit:
    key: HKCU:\Control Panel\Desktop
    value: TileWallpaper
    data: 0

- name: install libreoffice
  win_chocolatey:
    name: libreoffice
    state: present

- name: create user opiskelija
  win_user:
    name: opiskelija
    password: salainen
    state: present
    groups:
      - Users
