#!/bin/bash

mkdir /home/joona/.ssh

chown joona /home/joona/.ssh

cat <<EOF > /home/joona/.ssh/authorized_keys

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfr7ZiTa2/dj9mH3UVdOvQO7uitaqRD7U5mtQO/7yE4waw8aKuRxc5XCSafi1nr1l577mQVwefT9AKIoBFz9XbMk3f49fap0/kxoJ0iN70PIo22m3tVOGOh3roZAzcNQA/TKFI8QTORx7f7YlYPqi1wwdZwPh2TNoAoOwhVVL3Pj7SI1zCZB8FaEfJ/GFU6gIqHQG9NhZo3gFYZaSw8V7mY673HZUNXeyRqoFjvtwjVc06XB17xLOUeuLtk2iLF6hqdam8WlH1yh3K7VKA3L9MpDOquHY8uO6+kOvt+wo5XAEIh+I2sKVRu0XtGLz+tzc95kOLj9HXfr5VL8J1StQX joona@ansiblemaster

EOF


chown joona /home/joona/.ssh/authorized_keys

mkdir /etc/ansible/local

cat <<EOF > /etc/cron.d/ansible-pull

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

*/5 * * * * root ansible-pull -o -d /etc/ansible/local -U git://github.com/joonaleppalahti/ansible-pull.git >>/var/log/ansible-pull.log 2>&1

EOF

cat <<EOF > /etc/logrotate.d/ansible-pull

/var/log/ansible-pull.log {
  rotate 7
  daily
  compress
  missingok
  notifempty
}

EOF

sleep 30

ansible-pull -d /etc/ansible/local -U git://github.com/joonaleppalahti/ansible-pull.git >>/var/log/ansible-pull.log 2>&1

sleep 15

ansible-pull -d /etc/ansible/local -U git://github.com/joonaleppalahti/ansible-pull.git >>/var/log/ansible-pull.log 2>&1

rm /etc/init.d/firstboot
update-rc.d firstboot remove
